services:

  database:
    container_name: database
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  api:
    ports:
      - "3000:3000"
      - "3001:3001"
    build: .
    volumes:
      - ./src/:/app/src
      - ./package.json:/app/package.json
    env_file:
      - .env
    depends_on:
      - database